language: java

sudo: required

jdk:
  - oraclejdk8
  
services:
  - docker

before_install:
  - export APP_VERSION=`git describe --tag --long`
  - export BUILT_ON=`TZ=Australia/Sydney date +%Y-%m-%d-%H%M` 
  - export BUILT_USING=`javac -version`
  - echo $APP_VERSION - $BUILT_ON - $BUILT_USING
  - sed -i "s|@APP.VERSION@|$APP_VERSION|" src/main/java/wenism/JavaWebHello.java
  - sed -i "s|@BUILT.ON@|$BUILT_ON|" src/main/java/wenism/JavaWebHello.java
  - sed -i "s|@BUILT.USING@|$BUILT_USING|" src/main/java/wenism/JavaWebHello.java

after_success:
  - docker build -t wenism/javawebhello:$APP_VERSION .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push wenism/javawebhello:$APP_VERSION